services:
  - type: web
    name: mobile-cicd-admin
    runtime: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3000
      - key: BASE_URL
        value: https://mobile-cicd-admin.onrender.com
      - key: NODE_ENV
        value: production
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
