services:
  - type: web
    name: ota-app-distribution
    runtime: docker
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free # Đổi thành 'starter' nếu muốn gắn Persistent Disk lưu file lâu dài
    envVars:
      - key: PORT
        value: 3000
      - key: BASE_URL
        value: https://ota-distribution-v1.onrender.com # Thay bằng URL public thật của bạn
      - key: NODE_ENV
        value: production
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
    # disk:
    #   name: ota-storage
    #   mountPath: /app/server/uploads
    #   sizeGB: 10
